fix action.yml
Signed-off-by: Kent Huang <kent@infuseai.io>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -54,6 +54,13 @@ runs:
         response=$(curl -s -X GET -H "Authorization: Bearer $GITHUB_TOKEN" "${{ inputs.api_host }}/api/v2/github/${{ github.repository }}/verify-token")
         project_id=$(echo "$response" | jq -r '.project_id')
         organization_id=$(echo "$response" | jq -r '.organization_id')
+        if [[ "$project_id" == "null" || "$organization_id" == "null" ]]; then
+          echo "Error: Recce Cloud integration settings are not properly configured for this repository."
+          echo "### Recce Cloud CI/CD Action Error" >> $GITHUB_STEP_SUMMARY
+          echo "Recce Cloud integration settings are not properly configured for this repository. Please ensure that your Recce token is valid and that the repository is linked to a Recce Cloud project." >> $GITHUB_STEP_SUMMARY
+          exit 1
+        fi
+
 
         # Get the presigned URLs for uploading the manifest files
         if [ "${{ github.event_name }}" = "pull_request" ]; then
@@ -64,14 +71,14 @@ runs:
             "branch": "'"$branch_name"'",
             "pr_number": "'"$pr_number"'",
             "adapter_type": "'"$adapter_type"'",
-          }' "${{ inputs.api_host }}/api/v2/organizations/$organization_id/projects/$project_id/pr-branch-session" )
+          }' "${{ inputs.api_host }}/api/v2/organizations/$organization_id/projects/$project_id/touch-recce-session" )
         else
           echo "Uploading manifest for base session..."
           branch_name="${{ github.ref_name }}"
           response=$(curl -s -X POST -H "Authorization: Bearer ${{ inputs.recce_token }}" -H "Content-Type: application/json" -d '{
             "branch": "'"$branch_name"'",
             "adapter_type": "'"$adapter_type"'",
-          }' "${{ inputs.api_host }}/api/v2/organizations/$organization_id/projects/$project_id/pr-branch-session" )
+          }' "${{ inputs.api_host }}/api/v2/organizations/$organization_id/projects/$project_id/touch-recce-session" )
         fi
 
         # Upload the manifest.json file
@@ -80,7 +87,8 @@ runs:
         session_id=$(echo "$response" | jq -r '.session_id')
         if [[ "$manifest_upload_url" == "null" || "$catalog_upload_url" == "null" || "$session_id" == "null" ]]; then
           echo "Error: Failed to get upload URLs or session ID from Recce Cloud."
-          echo "### Recce Cloud CI/CD Action Error ###\nFailed to get upload URLs or session ID from Recce Cloud. Please check your Recce token and repository integration settings.\n### End of Error ###" >> $GITHUB_STEP_SUMMARY
+          echo "### Recce Cloud CI/CD Action Error" >> $GITHUB_STEP_SUMMARY
+          echo "Failed to get upload URLs or session ID from Recce Cloud. Please check your Recce token and repository integration settings." >> $GITHUB_STEP_SUMMARY
           exit 1
         fi
         curl -s -X PUT -H "Content-Type: application/json" --upload-file "${{ inputs.dbt_target_path }}/manifest.json" "$manifest_upload_url"
